# Generated by Django 5.2.4 on 2025-07-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dietplan_calories_dietplan_date_dietplan_meals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='date',
            field=models.DateField(),
        ),
    ]
